name: eocdb-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.6*
  #
  # runtime dependencies
  #
  - numpy =1.14.3
  - pyyaml =3.12
  - tornado =5.0.2
  #
  # development tools
  #
  - pytest =3.5.1
  - pytest-cov =2.5.1
  - flake8 =3.5.0
