store_path: ~/.eocdb/store

users:
  - name: scott
    id: 1
    first_name: Bruce
    last_name: Scott
    email: bruce.scott@gmail.com
    phone: "+34 5678901234"
    password: tiger
    roles:
      - submit
      - admin

databases:
  default:
    type: eocdb.db.mongo_db_driver.MongoDbDriver
    primary: true
    parameters:
        url: "mongodb://10.3.0.107:27017/eocdb"

